using System;
using System.Collections.Generic;
using System.Text;

namespace CodeConvention.LazyLoding.Models
{
    public class ManagerLazyLoading
    {
        public string Name { get; set; }

        private List<Employees> EmployeesLazyLodings = null;

        private Lazy<List<Employees>> EmployeesLazy;

        public List<Employees> EmployeesProperty
        {
            get
            {
                return EmployeesLazy.Value;
            }
        }

        public ManagerLazyLoading()
        {
            Name = "Mr.Bond";
            EmployeesLazy = new Lazy<List<Employees>>(() => LoadEmployees());
        }


        public List<Employees> EmployeesListLazy
        {
            get
            {
                if (EmployeesLazyLodings == null)
                    EmployeesLazyLodings = LoadEmployees();
                return EmployeesLazyLodings;
            }
        }



        private List<Employees> LoadEmployees()
        {
            return new List<Employees>()
            {
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "James"},
                new Employees () {EmployeeName = "Catherine"},
                new Employees () {EmployeeName = "Anthony"},
                new Employees () {EmployeeName = "Peter"},
                new Employees () {EmployeeName = "Paul"},
                new Employees () {EmployeeName = "Catherine"}
            };
        }
    }
}
